name: 'dangdennis/toml-reader'
description: 'Read a specific field from a TOML file'
branding:
  icon: file-text
  color: gray-dark
inputs:
  file:
    description: 'The TOML file to read from'
    required: true
  field:
    description: 'The field inside the TOML file to read'
    required: true
  working-directory:
    description: 'The working directory where the TOML file resides'
    required: false
outputs:
  value:
    description: 'The data stored in `field` inside `file`'
runs:
  using: 'node12'
  main: 'index.js'

